sublist = [
            'funny',
            'adviceanimals',
            'pics',
            'aww',
            'blackpeopletwitter',
            'todayilearned',
            'wtf',
            'gifs',
            'videos',
            'gaming',
            'askreddit',
            'leagueoflegends',
            'worldnews',
            'trees',
            'trollxchromosomes',
            'mildlyinteresting',
    #       'pcmasterrace',     #they don't allow links in posts
            'soccer',
            '4chan',
            'news',
            'showerthoughts',
            'politics',
            'dota2',
            'fatpeoplehate',
            'movies',
            'nba',
            'pokemon',
            'science',
            'technology',
            'woahdude',
            'jokes',
            'globaloffensive',
            'tumblrinaction',
            'unexpected',
            'earthporn',
            'iama',
            'atheism',
            'tifu',
            'nottheonion',
            'reactiongifs',
            'squaredcircle',
            'tumblr',
            'destinythegame',
            'nfl',
            'cats',
            'gentlemanboners',
            'makeupaddiction',
            'celebs',
            'smashbros',
            'interestingasfuck',
            'circlejerk',
            'me_irl',
            'food',
            'cringepics',
            'oddlysatisfying',
            'explainlikeimfive',
            'hockey',
            'kotakuinaction',
            'games',
            'conspiracy',
            'creepy',
            'wow',
            'tinder',
            'justiceporn',
            'firstworldanarchists',
            'android',
            'hearthstone',
            'skyrim',
            'minecraft',
            'oldschoolcool',
            'polandball',
            'relationships',
            'hiphopheads',
            'mildlyinfuriating',
            'writingprompts',
            'coys',
            'anime',
            'photoshopbattles',
            'twoxchromosomes',
            'historyporn',
            'roosterteeth',
            'comics',
            'youtubehaiku',
            'tf2',
            'teenagers',
            'lifeprotips',
            'bestof',
            'magictcg',
            'starwars',
            'bindingofisaac',
            'india',
            'askscience',
            'thathappened',
            'australia',
            'unexpectedthuglife',
            'ps4',
            'patriots',
            #'trashy',               #they don't like us a lot :/
            'getmotivated',
            'foodporn',
            'childfree',
            #'tattoos',             #not a lot of good comments
            #'shittyreactiongifs',  #relatively few good comments
            'music',
            #'awwnime',             #very few good comments
            'bitcoin',
            'talesfromretail',
            'xboxone',
            'futurology',
            'murica',
            #'fatlogic',            #rule against linking other subs (brigade accusations)
            'podemos',
            'starcraft',
            'facepalm',
            'kerbalspaceprogram',
            'ladyboners',
            'dataisbeautiful',
            'justneckbeardthings',
            'thesimpsons',
            'sneakers',
            'militaryporn',
            'creepypms',
            'cringe',
            'thelastairbender',
            'justrolledintotheshop',
            'wheredidthesodago',
            'nosleep',
            'talesfromtechsupport',
            'cosplaygirls',
            'television',
            'shittyaskscience',
            'crappydesign',
            'space',
            'askhistorians',
            'progresspics',
            'art',
            'trollychromosome',
            'gunners',
            'diy',
            'standupshots',
            'quotesporn',
            'electronic_cigarette',
            'redditlaqueristas',
            'cfb',
            '2007scape',
            'punchablefaces',
            'gamegrumps',
            'canada',
            'watchitfortheplot',
            'shittyfoodporn',
            'sweden',
            'mylittlepony',
            'fffffffuuuuuuuuuuuu',
            'animalsbeingjerks',
            'sports',
            'itookapicture',
            'battlestations',
            'europe',
            'gamedeals',
            'h1z1',
            'smite',
            'mapporn',
            'subredditdrama',
            'amiibo',
            'wallpapers',
            'prettygirls',
            'guns',
            'grandtheftautov',
            'runescape',
            'mma',
            'sex',
            'internetisbeautiful',
            'youdontsurf',
            'thewalkingdead',
            'formula1',
            #'carporn',         #a very quiet sub
            #'netflixbestof',   #few good comments
            'fifa'
            #'eyebleach'        #nothing good
        ]

def check_sublist_consistency():

    print "sublist has %d subs."%len(sublist)

    if len(set(sublist)) < len(sublist):
        print "sublist has duplicates."
        
        di = None
        dc = {}
        for i in range(len(sublist)):
            if sublist[i] in dc:
                di = i
                break
            else:
                dc[sublist[i]] = 1

        print "one of the duplicates is /r/%s"%sublist[di]
